/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Class.ConnectionProvider;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JOptionPane;

/**
 *
 * @author PraveenKumar
 */
public class ProfileSetting extends javax.swing.JFrame {

    /**
     * Creates new form StaffUpdate
     */
    String ImagePth = null;
    boolean address_result;
    boolean empty_result;
    boolean fname_result;
    boolean lname_result;
    boolean password_result;
    boolean rep_password_result;
    boolean contact_result;
    ImageIcon icon = null;

    public ProfileSetting() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

        try {

            Connection con = ConnectionProvider.getInstance().getDBConnection();
            String query = "SELECT * FROM user WHERE email ='" + SignIn.sessionEmail + "' AND position ='" + SignIn.sessionPosition + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            if (rs.next()) {
                ImagePth = rs.getString("profilepic");
                ProfilePicImg.setIcon(resizePic(ImagePth));

                Email.setText(rs.getString("email"));
                FirstName.setText(rs.getString("firstname"));
                LastName.setText(rs.getString("lastname"));
                Password.setText(rs.getString("password"));
                RepPassword.setText(rs.getString("password"));
                Position.setText(rs.getString("position"));
                Address.setText(rs.getString("address"));
                SecurityQuestion.setSelectedItem(rs.getString("question"));
                QuestionAnswer.setText(rs.getString("answer"));
                ContactNo.setText(rs.getString("contactno"));
            } else {
                JOptionPane.showMessageDialog(null, "User Not Found");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ProfilePicImg = new javax.swing.JLabel();
        AddProfilePicBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Goback = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Commonlbl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        SecurityQuestion = new javax.swing.JComboBox<>();
        RegisterBtn = new javax.swing.JButton();
        RepPassword = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Position = new javax.swing.JTextField();
        QuestionAnswer = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        answerlbl = new javax.swing.JLabel();
        ContactNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NA | User Profile");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 31, 63));

        ProfilePicImg.setBackground(new java.awt.Color(0, 31, 63));
        ProfilePicImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/userlogin.png"))); // NOI18N
        ProfilePicImg.setOpaque(true);

        AddProfilePicBtn.setBackground(new java.awt.Color(0, 31, 63));
        AddProfilePicBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        AddProfilePicBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddProfilePicBtn.setText("Add Profile Picture");
        AddProfilePicBtn.setBorder(null);
        AddProfilePicBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddProfilePicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProfilePicBtnActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 31, 63));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Profile Setting");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Inventory Management System");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Goback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/goBack.png"))); // NOI18N
        Goback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GobackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Goback)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(ProfilePicImg)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(AddProfilePicBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Goback)
                .addGap(18, 18, 18)
                .addComponent(ProfilePicImg, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(AddProfilePicBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(145, 145, 145))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1320, 851));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 38)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("My Profile");

        Commonlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Commonlbl.setForeground(new java.awt.Color(204, 0, 0));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel5.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanel5.setPreferredSize(new java.awt.Dimension(1200, 350));

        SecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select a Security Question", "What was the name of your elementary school?", "What was your childhood nickname?", "Who was your childhood hero?" }));
        SecurityQuestion.setBorder(null);
        SecurityQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        RegisterBtn.setBackground(new java.awt.Color(0, 31, 63));
        RegisterBtn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        RegisterBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegisterBtn.setText("Update Profile");
        RegisterBtn.setBorder(null);
        RegisterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        RepPassword.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        RepPassword.setForeground(new java.awt.Color(51, 51, 51));
        RepPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RepPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        RepPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RepPasswordKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Security Question");

        FirstName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstName.setForeground(new java.awt.Color(51, 51, 51));
        FirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FirstName.setAlignmentX(1.0F);
        FirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        FirstName.setMaximumSize(new java.awt.Dimension(6, 12));
        FirstName.setMinimumSize(new java.awt.Dimension(6, 12));
        FirstName.setName(""); // NOI18N
        FirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FirstNameKeyReleased(evt);
            }
        });

        LastName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LastName.setForeground(new java.awt.Color(51, 51, 51));
        LastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LastName.setAlignmentX(1.0F);
        LastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        LastName.setMaximumSize(new java.awt.Dimension(6, 12));
        LastName.setMinimumSize(new java.awt.Dimension(6, 12));
        LastName.setName(""); // NOI18N
        LastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LastNameKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Position");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Repeat Password");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Address");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("First Name");

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("last Name");

        Position.setEditable(false);
        Position.setBackground(new java.awt.Color(224, 223, 223));
        Position.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Position.setForeground(new java.awt.Color(51, 51, 51));
        Position.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Position.setAlignmentX(1.0F);
        Position.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        Position.setMaximumSize(new java.awt.Dimension(6, 12));
        Position.setMinimumSize(new java.awt.Dimension(6, 12));
        Position.setName(""); // NOI18N

        QuestionAnswer.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        QuestionAnswer.setForeground(new java.awt.Color(51, 51, 51));
        QuestionAnswer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QuestionAnswer.setAlignmentX(1.0F);
        QuestionAnswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        QuestionAnswer.setMaximumSize(new java.awt.Dimension(6, 12));
        QuestionAnswer.setMinimumSize(new java.awt.Dimension(6, 12));
        QuestionAnswer.setName(""); // NOI18N

        Password.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(51, 51, 51));
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordKeyReleased(evt);
            }
        });

        Email.setEditable(false);
        Email.setBackground(new java.awt.Color(224, 223, 223));
        Email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(51, 51, 51));
        Email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Email.setAlignmentX(1.0F);
        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        Email.setMaximumSize(new java.awt.Dimension(6, 12));
        Email.setMinimumSize(new java.awt.Dimension(6, 12));
        Email.setName(""); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Email");

        answerlbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        answerlbl.setForeground(new java.awt.Color(51, 51, 51));
        answerlbl.setText("Answer");

        ContactNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ContactNo.setForeground(new java.awt.Color(51, 51, 51));
        ContactNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContactNo.setAlignmentX(1.0F);
        ContactNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        ContactNo.setMaximumSize(new java.awt.Dimension(6, 12));
        ContactNo.setMinimumSize(new java.awt.Dimension(6, 12));
        ContactNo.setName(""); // NOI18N
        ContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ContactNoKeyReleased(evt);
            }
        });

        Address.setColumns(20);
        Address.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Address.setForeground(new java.awt.Color(51, 51, 51));
        Address.setRows(5);
        Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 179, 179)));
        Address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AddressKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Address);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Password");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Contact Number");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(80, 80, 80)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addComponent(answerlbl)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(RepPassword)
                    .addComponent(QuestionAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(7, 7, 7)
                        .addComponent(RepPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(answerlbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QuestionAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(RegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Commonlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(Commonlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ImageIcon resizePic(String picPath) {
        ImageIcon myImg = new ImageIcon(picPath);
        Image img = myImg.getImage().getScaledInstance(ProfilePicImg.getWidth(), ProfilePicImg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon myPicture = new ImageIcon(img);
        return myPicture;
    }

    private void AddProfilePicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProfilePicBtnActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("*.Images", "jpg", "png");
        chooser.addChoosableFileFilter(fileFilter);

        int fileState = chooser.showSaveDialog(null);

        if (icon == null) {
            if (fileState == JFileChooser.APPROVE_OPTION) {
                File f = chooser.getSelectedFile();
                String path = f.getAbsolutePath();
                ImagePth = path;

                //display img
                ProfilePicImg.setIcon(resizePic(path));
            }
        }
    }//GEN-LAST:event_AddProfilePicBtnActionPerformed

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        String UserID = Email.getText();
        String fname = FirstName.getText();
        String lname = LastName.getText();
        String password = String.valueOf(Password.getPassword());
        String rep_password = String.valueOf(RepPassword.getPassword());
        String address = Address.getText();
        String question = String.valueOf(SecurityQuestion.getSelectedItem());
        String answer = QuestionAnswer.getText();
        String contactno = ContactNo.getText();

        if (fname_result) {
            JOptionPane.showMessageDialog(null, "First Name must have Alphabet Characters Only");
        }

        if (lname_result) {
            JOptionPane.showMessageDialog(null, "Last Name must have Alphabet Characters Only");
        }

        if (password_result) {
            JOptionPane.showMessageDialog(null, "Password required at least 1 uppercase and 1 lowercase,1 digit, 1 symbol(@#$%^&+=),length from 8 to 20");
        }

        if (!rep_password.equals(password)) {
            JOptionPane.showMessageDialog(null, "Password does not match");
        }

        if (address_result) {
            JOptionPane.showMessageDialog(null, "Enter Valid Address");
        }

        if (contact_result) {
            JOptionPane.showMessageDialog(null, "Contact Number is Invalid");
        }

        if (question.equalsIgnoreCase("Please select a Security Question")) {
            JOptionPane.showMessageDialog(null, "Please select a Security Question");
        }

        if (ImagePth == null) {
            JOptionPane.showMessageDialog(null, "Please Add Profile Picture");
        }

        if (UserID.isEmpty() || fname.isEmpty() || lname.isEmpty() || answer.isEmpty() || address.isEmpty() || contactno.isEmpty() || password.isEmpty() || rep_password.isEmpty()) {
            empty_result = true;
            JOptionPane.showMessageDialog(null, "Empty Input Field");
        } else {
            empty_result = false;
        }

        if (address_result == false && empty_result == false && lname_result == false && fname_result == false && password_result == false && contact_result == false && rep_password_result == false && ImagePth != null) {
            try {
                Connection con = ConnectionProvider.getInstance().getDBConnection();
                String query = "UPDATE user SET firstname=?,lastname=?,password=?,profilepic=?,contactno=?,address=?,question=?,answer=? WHERE email='" + UserID + "'";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, fname);
                ps.setString(2, lname);
                ps.setString(3, password);
                ps.setString(4, ImagePth);
                ps.setString(5, contactno);
                ps.setString(6, address);
                ps.setString(7, question);
                ps.setString(8, answer);

                if (ps.executeUpdate() != 0) {
                    JOptionPane.showMessageDialog(null, "Account Updated");
                } else {
                    JOptionPane.showMessageDialog(null, "Error : DataBase Connectivity Problem");
                }
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void RepPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RepPasswordKeyReleased
        String password = String.valueOf(Password.getPassword());
        String rep_password = String.valueOf(RepPassword.getPassword());

        rep_password_result = !password.equals(rep_password);

        if (rep_password_result) {
            Commonlbl.setForeground(Color.red);
            Commonlbl.setText("Password does not match");
        } else {
            Commonlbl.setText(null);
        }
    }//GEN-LAST:event_RepPasswordKeyReleased

    private void FirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstNameKeyReleased
        String fname = FirstName.getText();
        String PATTERN = "^[a-zA-z]+$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(fname);

        fname_result = !match.matches();

        if (fname_result) {
            Commonlbl.setForeground(Color.red);
            Commonlbl.setText("First Name is not Correct");
        } else {
            Commonlbl.setText(null);
        }
    }//GEN-LAST:event_FirstNameKeyReleased

    private void LastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameKeyReleased
        String lname = LastName.getText();
        String PATTERN = "^[a-zA-z]+$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(lname);

        lname_result = !match.matches();

        if (lname_result) {
            Commonlbl.setForeground(Color.red);
            Commonlbl.setText("Last Name is not Correct");
        } else {
            Commonlbl.setText(null);
        }
    }//GEN-LAST:event_LastNameKeyReleased

    private void PasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyReleased
        String password = String.valueOf(Password.getPassword());
        int pass_length = password.length();

        String PATTERN = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,20}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(password);

        password_result = !match.matches();

        if (password_result) {
            Commonlbl.setForeground(Color.red);
            Commonlbl.setText("<html>Password required at least 1 uppercase and <br> 1 lowercase,1 digit, 1 symbol(@#$%^&+=),<br>length from 8 to 20</html>");
        } else {
            Commonlbl.setText(null);
        }
    }//GEN-LAST:event_PasswordKeyReleased

    private void ContactNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactNoKeyReleased
        String contactno = ContactNo.getText();
        String PATTERN = "^[0-9]{10}+$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(contactno);

        contact_result = !match.matches();

        if (contact_result) {
            Commonlbl.setForeground(Color.red);
            Commonlbl.setText("Contact Number is Invalid (Maximum Length = 10)");
        } else {
            Commonlbl.setText(null);
        }
    }//GEN-LAST:event_ContactNoKeyReleased

    private void GobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GobackMouseClicked
        Settings userDBoard = new Settings();
        userDBoard.setVisible(true);
        userDBoard.pack();
        userDBoard.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        userDBoard.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_GobackMouseClicked

    private void AddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddressKeyReleased
        String address = Address.getText();
        String PATTERN = "^[a-zA-Z0-9/\\s,.'-]*$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(address);

        address_result = !match.matches();

        if (address_result) {
            Commonlbl.setForeground(Color.red);
            Commonlbl.setText("Address Field is not Correct");
        } else {
            Commonlbl.setText(null);
        }
    }//GEN-LAST:event_AddressKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileSetting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProfilePicBtn;
    private javax.swing.JTextArea Address;
    private javax.swing.JLabel Commonlbl;
    private javax.swing.JTextField ContactNo;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FirstName;
    private javax.swing.JLabel Goback;
    private javax.swing.JTextField LastName;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Position;
    private javax.swing.JLabel ProfilePicImg;
    private javax.swing.JTextField QuestionAnswer;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JPasswordField RepPassword;
    private javax.swing.JComboBox<String> SecurityQuestion;
    private javax.swing.JLabel answerlbl;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
