/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Class.ConnectionProvider;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Faizur Rahman
 */
public class report extends javax.swing.JFrame {
    Connection conn= null;
    ResultSet rs =null;

    PreparedStatement pst = null;
    /**
     * Creates new form report
     */
    public report() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SerCom = new javax.swing.JButton();
        RepCom = new javax.swing.JButton();
        serful = new javax.swing.JButton();
        Repfull = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        SerCom.setBackground(new java.awt.Color(255, 255, 255));
        SerCom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SerCom.setForeground(new java.awt.Color(51, 0, 102));
        SerCom.setText("Report for completed services");
        SerCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerComActionPerformed(evt);
            }
        });

        RepCom.setBackground(new java.awt.Color(255, 255, 255));
        RepCom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RepCom.setForeground(new java.awt.Color(51, 0, 102));
        RepCom.setText("Report for completed repairs");
        RepCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepComActionPerformed(evt);
            }
        });

        serful.setBackground(new java.awt.Color(255, 255, 255));
        serful.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        serful.setForeground(new java.awt.Color(51, 0, 102));
        serful.setText("Service full report");
        serful.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serfulActionPerformed(evt);
            }
        });

        Repfull.setBackground(new java.awt.Color(255, 255, 255));
        Repfull.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Repfull.setForeground(new java.awt.Color(51, 0, 102));
        Repfull.setText(" Repair full report");
        Repfull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepfullActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 102));
        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Entypo_d83d(0)_64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Repfull, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SerCom, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serful, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RepCom, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RepCom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(SerCom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Repfull, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(serful, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SerComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerComActionPerformed
        // TODO add your handling code here:
          try{
            Connection conn = ConnectionProvider.getInstance().getDBConnection();
            String rpt ="C:\\Users\\Roshan Nizar\\Documents\\NetBeansProjects\\IMS\\servicecompleted.jrxml";
            
            JasperReport jr =JasperCompileManager.compileReport(rpt);
            
            JasperPrint jp = JasperFillManager.fillReport(jr,null,conn);
            
            JasperViewer.viewReport(jp);
            
            
        }catch(Exception e){
        
        JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_SerComActionPerformed

    private void RepComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepComActionPerformed
        // TODO add your handling code here:
        
        try{
            Connection conn = ConnectionProvider.getInstance().getDBConnection();
            String rpt ="C:\\Users\\Roshan Nizar\\Documents\\NetBeansProjects\\IMS\\repaircompleted.jrxml";
            
            JasperReport jr =JasperCompileManager.compileReport(rpt);
            
            JasperPrint jp = JasperFillManager.fillReport(jr,null,conn);
            
            JasperViewer.viewReport(jp);
            
            
        }catch(Exception e){
        
        JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_RepComActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          Dashboard lg = new Dashboard();
                lg.setVisible(true);
            
                this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RepfullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepfullActionPerformed
        // TODO add your handling code here:
          
        try{
            Connection conn = ConnectionProvider.getInstance().getDBConnection();
            String rpt ="C:\\Users\\Roshan Nizar\\Documents\\NetBeansProjects\\IMS\\repairfullreport.jrxml";
            
            JasperReport jr =JasperCompileManager.compileReport(rpt);
            
            JasperPrint jp = JasperFillManager.fillReport(jr,null,conn);
            
            JasperViewer.viewReport(jp);
            
            
        }catch(Exception e){
        
        JOptionPane.showMessageDialog(null,e);
        }
       
    }//GEN-LAST:event_RepfullActionPerformed

    private void serfulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serfulActionPerformed
        // TODO add your handling code here:
        
          
        try{
            Connection conn = ConnectionProvider.getInstance().getDBConnection();
            String rpt ="C:\\Users\\Roshan Nizar\\Documents\\NetBeansProjects\\IMS\\servicefullreport.jrxml";
            
            JasperReport jr =JasperCompileManager.compileReport(rpt);
            
            JasperPrint jp = JasperFillManager.fillReport(jr,null,conn);
            
            JasperViewer.viewReport(jp);
            
            
        }catch(Exception e){
        
        JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_serfulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RepCom;
    private javax.swing.JButton Repfull;
    private javax.swing.JButton SerCom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton serful;
    // End of variables declaration//GEN-END:variables
}
