/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Class.ConnectionProvider;
import Class.SendEmail;
import com.orsonpdf.PDFDocument;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.io.*;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Faizur Rahman
 */
public class Service extends javax.swing.JFrame {
      Connection conn= null;
    ResultSet rs =null;
    ResultSet rss =null;
    PreparedStatement pst = null;
    PreparedStatement pstt = null;
    /**
     * Creates new form Service
     */
    public Service() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size =toolkit.getScreenSize();
        Update_table();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }
    
    
    private void Update_table(){
        try{
            Connection conn = ConnectionProvider.getInstance().getDBConnection();
            String sql = "select * from service";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            servicetable.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){}
        }
        
        
        
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        servicetable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        service = new javax.swing.JTextField();
        tech = new javax.swing.JTextField();
        CustomId = new javax.swing.JTextField();
        product = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        Add = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        rdate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        tech1 = new javax.swing.JTextField();
        service1 = new javax.swing.JTextField();
        product1 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        date1 = new javax.swing.JTextField();
        status1 = new javax.swing.JComboBox<>();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        Clear1 = new javax.swing.JButton();
        report = new javax.swing.JButton();
        CustomId1 = new javax.swing.JTextField();
        rdate1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1315, 681));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(750, 272));

        jScrollPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jScrollPane1KeyReleased(evt);
            }
        });

        servicetable.setBackground(new java.awt.Color(204, 204, 255));
        servicetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        servicetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servicetableMouseClicked(evt);
            }
        });
        servicetable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                servicetableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(servicetable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(960, 564));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Service ID:");

        service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serviceMouseEntered(evt);
            }
        });
        service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceActionPerformed(evt);
            }
        });
        service.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serviceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serviceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serviceKeyTyped(evt);
            }
        });

        tech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                techActionPerformed(evt);
            }
        });
        tech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                techKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                techKeyTyped(evt);
            }
        });

        CustomId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CustomIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CustomIdKeyTyped(evt);
            }
        });

        product.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Technician Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Customer ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Product ID:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("ReturnDate:");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Date:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Status:");

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Completed", "Cancelled" }));
        status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                statusKeyReleased(evt);
            }
        });

        Add.setBackground(new java.awt.Color(255, 51, 51));
        Add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/if_Add_131846.png"))); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 51, 51));
        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/if_Erase_131842.png"))); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        date.setDateFormatString("yyyy-MM-dd");

        rdate.setDateFormatString("yyyy-MM-dd");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Price");

        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7))
                            .addGap(51, 51, 51)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tech, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(service, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CustomId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rdate, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(service, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(rdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tech, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CustomId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(449, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(960, 564));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 153));
        jLabel43.setText("Service ID:");

        tech1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tech1MouseClicked(evt);
            }
        });
        tech1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tech1ActionPerformed(evt);
            }
        });
        tech1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tech1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tech1KeyTyped(evt);
            }
        });

        service1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service1ActionPerformed(evt);
            }
        });
        service1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                service1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                service1KeyTyped(evt);
            }
        });

        product1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                product1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                product1KeyTyped(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 153));
        jLabel44.setText("Technician Name:");

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 153));
        jLabel45.setText("Customer ID:");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 153));
        jLabel46.setText("Product ID:");

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 153));
        jLabel47.setText("ReturnDate:");

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 153));
        jLabel49.setText("Date:");

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 153));
        jLabel51.setText("Status:");

        date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date1ActionPerformed(evt);
            }
        });
        date1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                date1KeyReleased(evt);
            }
        });

        status1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Completed", "Cancelled" }));
        status1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status1ActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(255, 51, 51));
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/if_Refresh_131707.png"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 51, 51));
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/if_Delete_131713.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 153));
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/if_Search_131849.png"))); // NOI18N
        jLabel52.setText("Search ID:");

        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKeyTyped(evt);
            }
        });

        Clear1.setBackground(new java.awt.Color(255, 51, 51));
        Clear1.setForeground(new java.awt.Color(255, 255, 255));
        Clear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/if_Erase_131842.png"))); // NOI18N
        Clear1.setText("Clear");
        Clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear1ActionPerformed(evt);
            }
        });

        report.setBackground(new java.awt.Color(255, 51, 51));
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setText("Report");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });

        CustomId1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CustomId1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CustomId1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46)
                    .addComponent(jLabel49))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(date1)
                        .addGap(961, 961, 961))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(service1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tech1))
                                .addGap(56, 56, 56))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(product1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CustomId1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(46, 46, 46)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(Clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(603, 603, 603))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(62, 62, 62)
                                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel47)
                                        .addComponent(jLabel51))
                                    .addGap(38, 38, 38)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(rdate1)
                                        .addComponent(status1, 0, 150, Short.MAX_VALUE))
                                    .addGap(0, 0, Short.MAX_VALUE)))))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(rdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(service1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51)
                    .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(tech1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(CustomId1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(product1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(427, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(0, 51, 102));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Services");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE))
                .addContainerGap(554, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serviceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceMouseEntered
        // TODO add your handling code here:

      
    }//GEN-LAST:event_serviceMouseEntered

    private void serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceActionPerformed

    private void serviceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serviceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceKeyPressed

    private void serviceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serviceKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){

            tech.requestFocus();

        }
    }//GEN-LAST:event_serviceKeyReleased

    private void techActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_techActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_techActionPerformed

    private void techKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_techKeyReleased
        // TODO add your handling code here:

        if(evt.getKeyCode()==KeyEvent.VK_DOWN){

            CustomId.requestFocus();
        }

        else if(evt.getKeyCode()==KeyEvent.VK_UP)
        {
            service.requestFocus();

        }
    }//GEN-LAST:event_techKeyReleased

    private void CustomIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CustomIdKeyReleased
        // TODO add your handling code here:

        if(evt.getKeyCode()==KeyEvent.VK_DOWN){

            product.requestFocus();
        }

        else if(evt.getKeyCode()==KeyEvent.VK_UP)
        {
            tech.requestFocus();

        }
    }//GEN-LAST:event_CustomIdKeyReleased

    private void productKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productKeyReleased
        // TODO add your handling code here:

         if(evt.getKeyCode()==KeyEvent.VK_UP)
        {
            CustomId.requestFocus();

        }
    }//GEN-LAST:event_productKeyReleased

    private void statusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statusKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_statusKeyReleased

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
if(!(service.getText().isEmpty()||tech.getText().isEmpty()||CustomId.getText().isEmpty()||product.getText().isEmpty()||((JTextField)date.getDateEditor().getUiComponent()).getText().isEmpty()||((JTextField)rdate.getDateEditor().getUiComponent()).getText().isEmpty()))
{
        int x = JOptionPane.showConfirmDialog(null, "Are you sure?","Add Record",JOptionPane.YES_NO_OPTION);
        if(x==0){

            try{
                Connection conn = ConnectionProvider.getInstance().getDBConnection();

                String sql ="insert into service(serviceid,technician,customerid,productid,date,returndate,amount,status)"
                +"values(?,?,?,?,?,?,?,?)";

                pst=conn.prepareStatement(sql);
                pst.setString(1,service.getText());
                pst.setString(2,tech.getText());
               
                pst.setString(3,CustomId.getText());
                pst.setString(4,product.getText());
               
               
                pst.setString(5,((JTextField)date.getDateEditor().getUiComponent()).getText());
                 pst.setString(6,((JTextField)rdate.getDateEditor().getUiComponent()).getText());
               pst.setString(7, price.getText());
                pst.setString(8,status.getSelectedItem().toString());

                pst.execute();

                conn.close();

                JOptionPane.showMessageDialog(null, "success");

            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);

            }
            finally{

                try{

                    rs.close();
                    pst.close();

                }catch(Exception e){

                }

            }
        }   Update_table();
} else{
    JOptionPane.showMessageDialog(null, "Fill All The Fields");
}
    }//GEN-LAST:event_AddActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
     service.setText("");
        tech.setText("");
       
        CustomId.setText("");
        product.setText("");
       
      
        date.setDateFormatString("");
           rdate.setDateFormatString("");
    }//GEN-LAST:event_clearActionPerformed

    private void tech1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tech1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_tech1MouseClicked

    private void tech1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tech1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tech1ActionPerformed

    private void tech1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tech1KeyReleased
        // TODO add your handling code here:

        if(evt.getKeyCode()==KeyEvent.VK_DOWN){

            CustomId1.requestFocus();
        }

        else if(evt.getKeyCode()==KeyEvent.VK_UP)
        {
            service1.requestFocus();

        }
    }//GEN-LAST:event_tech1KeyReleased

    private void service1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_service1KeyReleased
        // TODO add your handling code here:

        if(evt.getKeyCode()==KeyEvent.VK_DOWN){

            tech1.requestFocus();
        }

        else if(evt.getKeyCode()==KeyEvent.VK_UP)
        {
            search.requestFocus();

        }
    }//GEN-LAST:event_service1KeyReleased

    private void product1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_product1KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){

            date1.requestFocus();
        }

        else if(evt.getKeyCode()==KeyEvent.VK_UP)
        {
            CustomId1.requestFocus();

        }
    }//GEN-LAST:event_product1KeyReleased

    private void date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date1ActionPerformed

    private void date1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date1KeyReleased
        // TODO add your handling code here:

        if(evt.getKeyCode()==KeyEvent.VK_DOWN){

            rdate1.requestFocus();
        }

        else if(evt.getKeyCode()==KeyEvent.VK_UP)
        {
            product1.requestFocus();

        }
    }//GEN-LAST:event_date1KeyReleased

    private void status1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         if(!(service1.getText().isEmpty()||tech1.getText().isEmpty()||CustomId1.getText().isEmpty()||product1.getText().isEmpty()||date1.getText().isEmpty()||rdate1.getText().isEmpty()))
         {
        int x = JOptionPane.showConfirmDialog(null, "Are you sure?","Update Record",JOptionPane.YES_NO_OPTION);
        if(x==0){
            try{
                Connection conn = ConnectionProvider.getInstance().getDBConnection();
               String val = service1.getText();
                String val1 = tech1.getText();
                String val2 =CustomId1.getText();
               
                
                String val3 = product1.getText();
             
                String val4 = date1.getText();
                String val5 = rdate1.getText();
                String val6 = price.getText();
                String val7 =status1.getSelectedItem().toString();

                String sql= "update service set serviceid='"+val+"',technician='"+val1+"',customerid='"+val2+"',productid='"+val3+"',date='"+val4+"',returndate='"+val5+"',status='"+val7+"',amount= '"+val6+"'  where serviceid='"+val+"' ";
                  
                 pst=conn.prepareStatement(sql);
                  pst.execute();
                
              
                JOptionPane.showMessageDialog(null, "Record Updated");
                String access =(status1.getSelectedItem().toString());

                if(access=="Completed"){
                    
                    
                   
             
                    
                    String sql2 ="select email from customer where customerid='"+val2+"' ";
                    
                    
            pstt=conn.prepareStatement(sql2);
      
            rss=pstt.executeQuery();
            
            if(rss.next()){
              String mail=rss.getString("email");
             
              
            
            
            
            

                    SendEmail se= new SendEmail(mail,"Service Completion","Dear Customer\nyour product has been serviced\nPlease Come and Collect Your Product\n Repair  Id:"+service1.getText()+"\nProductId Id :"+product1.getText());
            }
              
                
                
            }
                
                else{}

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Record Update Unsuccessful");
                JOptionPane.showMessageDialog(null,e);
                System.out.print(e);

            }   finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){}
        }
        
        
        }
            Update_table();
         }else{
             JOptionPane.showMessageDialog(null, "Fill All The Fields");
         }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         if(!(service1.getText().isEmpty()))
         {
         int x = JOptionPane.showConfirmDialog(null, "Are you sure?","Delete Record",JOptionPane.YES_NO_OPTION);
        if(x==0){

            try{
                Connection conn = ConnectionProvider.getInstance().getDBConnection();

                String sql ="delete from service where serviceid=?";
                pst=conn.prepareStatement(sql);
                pst.setString(1,service1.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null,"Record Deleted");

                search.setText("");
                service1.setText("");
               
                tech1.setText("");
                CustomId1.setText("");
                product1.setText("");
              
                date1.setText("");
                rdate1.setText("");
                price.setText("");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }finally{
                try{
                    rs.close();
                    pst.close();
                }catch(Exception e){

                }
            }

        }
        Update_table();
         }else {
             JOptionPane.showMessageDialog(null, "Enter The Service ID");
         }
    }//GEN-LAST:event_deleteActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMouseClicked

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
        // TODO add your handling code here:
 
    }//GEN-LAST:event_searchMouseEntered

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:

         try{
            Connection conn = ConnectionProvider.getInstance().getDBConnection();

            String sql = "select * from service where serviceid =?";

            pst=conn.prepareStatement(sql);
            pst.setString(1,search.getText());
            ResultSet rs=pst.executeQuery();

            if(rs.next()){
                String add1=rs.getString("serviceid");
                service1.setText(add1);

                String add2=rs.getString("technician");
                tech1.setText(add2);
                
               ;

                String add3=rs.getString("customerid");
                CustomId1.setText(add3);

                String add4=rs.getString("productid");
                product1.setText(add4);

               

                String add7=rs.getString("date");
                date1.setText(add7);

                String add8=rs.getString("returndate");
             
                rdate1.setText(add8);
                
                String add9 = rs.getString("amount");
                price.setText(add9);

                String add10=rs.getString("status");
                status1.setSelectedItem(add10);

            }else{ }
        }catch(Exception e){

        }
        finally{

            try{

                rs.close();
                pst.close();

            }catch(Exception e){

            }

        }
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){

            tech1.requestFocus();
        }
    }//GEN-LAST:event_searchKeyReleased

    private void searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyTyped
        // TODO add your handling code here:
          char id =evt.getKeyChar();
        if(!(Character.isDigit(id) || (id==KeyEvent.VK_BACK_SPACE)|| id==KeyEvent.VK_DELETE)){
             getToolkit().beep();
              JOptionPane.showMessageDialog(null,"Numeric Values Only");
             evt.consume();
        }
    }//GEN-LAST:event_searchKeyTyped

    private void Clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear1ActionPerformed
        // TODO add your handling code here:
        search.setText("");
        service1.setText("");
        
        tech1.setText("");
        CustomId1.setText("");
        product1.setText("");
       
        date1.setText("");
        rdate1.setText("");
        price.setText("");
        
    }//GEN-LAST:event_Clear1ActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
 if(!(service1.getText().isEmpty()||tech1.getText().isEmpty()||CustomId1.getText().isEmpty()||product1.getText().isEmpty()||date1.getText().isEmpty()||rdate1.getText().isEmpty() || price.getText().isEmpty()))
 {
        
       
            String val = service1.getText();
            String val2 =CustomId1.getText();
            String val1 = tech1.getText();
            String val3 = product1.getText();
      
            String val4 = date1.getText();
            String val5 = rdate1.getText();
            String val6 = price.getText();
       
            String val7 =status1.getSelectedItem().toString();

                     JFileChooser dialog = new JFileChooser();
                     dialog.setSelectedFile(new File(val+" "+"Service Details"+".pdf"));
                     int dialogResult =dialog.showSaveDialog(null);

        if(dialogResult == JFileChooser.APPROVE_OPTION){

               String filePath = dialog.getSelectedFile().getPath();
                   
            
            
                      try{
                 Connection conn = ConnectionProvider.getInstance().getDBConnection();
                 

            String sql = "select * from customer where customerid='"+val2+"' ";
      
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
     
      if(rs.next()){
      
           
            Document myDocument = new Document();
          PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));
              
            myDocument.open();
            myDocument.add(new Paragraph("                                          New AirTell",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
            myDocument.add(new Paragraph("Service Detail Of Id :"+val ,FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
            myDocument.add(new Paragraph(new Date().toString()));
            myDocument.add(new Paragraph("_____________________________________________________________________________"));
            myDocument.add(new Paragraph("CUSTOMER DETAILS",FontFactory.getFont(FontFactory.TIMES_BOLD,15,Font.BOLD)));
            myDocument.add(new Paragraph("Customer Firstname: "+rs.getString(2),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
            myDocument.add(new Paragraph("Customer Lastname: "+rs.getString(3),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
            myDocument.add(new Paragraph("Customer Email: "+rs.getString(4),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
            myDocument.add(new Paragraph("Customer ContactNo: "+rs.getString(6),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
             myDocument.add(new Paragraph("_____________________________________________________________________________"));
            myDocument.add(new Paragraph("SERVICE DETAILS",FontFactory.getFont(FontFactory.TIMES_BOLD,15,Font.BOLD)));
            myDocument.add(new Paragraph("Customer Id: "+val2,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
            myDocument.add(new Paragraph("Service Id: "+val,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
            myDocument.add(new Paragraph("Technician Name: "+val1,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
            myDocument.add(new Paragraph("Product Id: "+val3,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
            myDocument.add(new Paragraph("Date: "+val4,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
            myDocument.add(new Paragraph("ReturnDate: "+val5,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
            myDocument.add(new Paragraph("Amount: "+val6,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
            myDocument.add(new Paragraph("Status: "+val7,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
             myDocument.add(new Paragraph("_____________________________________________________________________________"));
      
            myDocument.close();
      
            JOptionPane.showMessageDialog(null, "Report was Successfully Generated");
      }              
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
 }else{
     JOptionPane.showMessageDialog(null, "All The Fields Has to be Filled In Order To Generate Report");
 }
    }//GEN-LAST:event_reportActionPerformed

    private void CustomId1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CustomId1KeyReleased
        // TODO add your handling code here:

        if(evt.getKeyCode()==KeyEvent.VK_DOWN){

            service1.requestFocus();
        }

        else if(evt.getKeyCode()==KeyEvent.VK_UP)
        {
            tech1.requestFocus();

        }
    }//GEN-LAST:event_CustomId1KeyReleased

    private void jScrollPane1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1KeyReleased

    private void servicetableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_servicetableKeyReleased
        // TODO add your handling code here:
          if(evt.getKeyCode()==KeyEvent.VK_DOWN||evt.getKeyCode()==KeyEvent.VK_UP){
             
              try{
            Connection conn = ConnectionProvider.getInstance().getDBConnection();
            
            
            
            int row= servicetable.getSelectedRow();
            String tab =(servicetable.getModel().getValueAt(row, 0).toString());
            String sql ="select * from service where serviceid='"+tab+"' ";
            
            
             pst=conn.prepareStatement(sql);
            
             ResultSet rs=pst.executeQuery();
           
            if(rs.next()){
            String add1=rs.getString("serviceid");
          service1.setText(add1);
            
           
            String add2=rs.getString("technician");
           tech1.setText(add2);
            
            String add3=rs.getString("customerid");
            CustomId1.setText(add3);
            
            String add4=rs.getString("productid");
            product1.setText(add4);
            
          
            
            String add7=rs.getString("date");
            date1.setText(add7);
            
            String add8=rs.getString("returndate");
            rdate1.setText(add8);
       
            String add9 = rs.getString("amount");
            price.setText(add9);
            
             String add10=rs.getString("status");
            status1.setSelectedItem(add10);
              
               
        
            }else{ }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         }
    }//GEN-LAST:event_servicetableKeyReleased

    private void servicetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicetableMouseClicked
        // TODO add your handling code here:
            try{
            Connection conn = ConnectionProvider.getInstance().getDBConnection();
            
            
            
            int row= servicetable.getSelectedRow();
            String tab =(servicetable.getModel().getValueAt(row, 0).toString());
            String sql ="select * from service where serviceid='"+tab+"' ";
            
            
             pst=conn.prepareStatement(sql);
            
             ResultSet rs=pst.executeQuery();
           
            if(rs.next()){
            String add1=rs.getString("serviceid");
          service1.setText(add1);
            
            String add2=rs.getString("technician");
           tech1.setText(add2);
           
         
            
            String add3=rs.getString("customerid");
            CustomId1.setText(add3);
            
            String add4=rs.getString("productid");
            product1.setText(add4);
            
           
            
            String add7=rs.getString("date");
            date1.setText(add7);
              String add8=rs.getString("returndate");
            rdate1.setText(add8);
            
       
            String add9 = rs.getString("amount");
            price.setText(add9);
            
             String add10=rs.getString("status");
            status1.setSelectedItem(add10);
              
               
        
            }else{ }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         
        
    }//GEN-LAST:event_servicetableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        More da = new More();
        da.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void serviceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serviceKeyTyped

          char id =evt.getKeyChar();
        if(!(Character.isDigit(id) || (id==KeyEvent.VK_BACK_SPACE)|| id==KeyEvent.VK_DELETE)){
             getToolkit().beep();
              JOptionPane.showMessageDialog(null,"Numeric Values Only");
             evt.consume();
        }
    }//GEN-LAST:event_serviceKeyTyped

    private void techKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_techKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_techKeyTyped

    private void CustomIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CustomIdKeyTyped
        // TODO add your handling code here:
          char id =evt.getKeyChar();
        if(!(Character.isDigit(id) || (id==KeyEvent.VK_BACK_SPACE)|| id==KeyEvent.VK_DELETE)){
             getToolkit().beep();
              JOptionPane.showMessageDialog(null,"Numeric Values Only");
             evt.consume();
        }
    }//GEN-LAST:event_CustomIdKeyTyped

    private void productKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productKeyTyped
        // TODO add your handling code here:
          char id =evt.getKeyChar();
        if(!(Character.isDigit(id) || (id==KeyEvent.VK_BACK_SPACE)|| id==KeyEvent.VK_DELETE)){
             getToolkit().beep();
              JOptionPane.showMessageDialog(null,"Numeric Values Only");
             evt.consume();
        }
    }//GEN-LAST:event_productKeyTyped

    private void service1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_service1KeyTyped
        // TODO add your handling code here:
          char id =evt.getKeyChar();
        if(!(Character.isDigit(id) || (id==KeyEvent.VK_BACK_SPACE)|| id==KeyEvent.VK_DELETE)){
             getToolkit().beep();
              JOptionPane.showMessageDialog(null,"Numeric Values Only");
             evt.consume();
        }
    }//GEN-LAST:event_service1KeyTyped

    private void tech1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tech1KeyTyped
        // TODO add your handling code here:
              char id =evt.getKeyChar();
        if(!(Character.isAlphabetic(id) || (id==KeyEvent.VK_BACK_SPACE)|| id==KeyEvent.VK_DELETE)){
             getToolkit().beep();
              JOptionPane.showMessageDialog(null,"Name Should be in Alphabetic");
             evt.consume();
        }
        
    }//GEN-LAST:event_tech1KeyTyped

    private void CustomId1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CustomId1KeyTyped
        // TODO add your handling code here:
                  char id =evt.getKeyChar();
        if(!(Character.isDigit(id) || (id==KeyEvent.VK_BACK_SPACE)|| id==KeyEvent.VK_DELETE)){
             getToolkit().beep();
              JOptionPane.showMessageDialog(null,"Numeric Values Only");
             evt.consume();
        }
    }//GEN-LAST:event_CustomId1KeyTyped

    private void product1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_product1KeyTyped
        // TODO add your handling code here:
                  char id =evt.getKeyChar();
        if(!(Character.isDigit(id) || (id==KeyEvent.VK_BACK_SPACE)|| id==KeyEvent.VK_DELETE)){
             getToolkit().beep();
              JOptionPane.showMessageDialog(null,"Numeric Values Only");
             evt.consume();
        }
    }//GEN-LAST:event_product1KeyTyped

    private void service1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_service1ActionPerformed

    private void priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_UP)
        {
            price.requestFocus();

        }
    }//GEN-LAST:event_priceKeyReleased

    private void priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyTyped
        char id =evt.getKeyChar();
        if(!(Character.isDigit(id) || (id==KeyEvent.VK_BACK_SPACE)|| id==KeyEvent.VK_DELETE)){
             getToolkit().beep();
              JOptionPane.showMessageDialog(null,"Numeric Values Only");
             evt.consume();
        }
    }//GEN-LAST:event_priceKeyTyped
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Service().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Clear1;
    private javax.swing.JTextField CustomId;
    private javax.swing.JTextField CustomId1;
    private javax.swing.JButton clear;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField date1;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price;
    private javax.swing.JTextField product;
    private javax.swing.JTextField product1;
    private com.toedter.calendar.JDateChooser rdate;
    private javax.swing.JTextField rdate1;
    private javax.swing.JButton report;
    private javax.swing.JTextField search;
    private javax.swing.JTextField service;
    private javax.swing.JTextField service1;
    private javax.swing.JTable servicetable;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JComboBox<String> status1;
    private javax.swing.JTextField tech;
    private javax.swing.JTextField tech1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
